on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

name: CV refresh

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages, render Rmarkdown CV file and Commit Results
        run: |
          echo "Rendering the page..."
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "scholar",
          "viteae", "stringr", "readr", "RefManageR", "tidyr", "dplyr", "gsheet"))'
          Rscript -e 'rmarkdown::render(input = "CV.Rmd")'
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add *
            git commit -m "Auto update CV"
            git push origin
          fi
